spring: 
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  # jsp 수정 후 새로고침 시 반영
  devtools.livereload.enabled: true
  # DB 연결 정보
  datasource:
    hikari: 
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password: 1234
  jpa:
    # 데이터 플랫폼 지정
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # 웹 요청이 완료될 때까지 영속성을 가짐 (성능상 안좋음)
    open-in-view: false
    hibernate:
      # 개발 초기 : create, update || 테스트 : update, validate || 운영 : validate, none
      # create-drop : create와 같으나 종료시점에 테이블 DROP
      ddl-auto: create-drop
    properties:
      hibernate:
        # 콘솔에 jpa 실행 쿼리
        show_sql: true
        # 쿼리를 가독성 있게 표현
        format_sql: true
        use_sql_comments: true
        
logging:
  level:
  # 로그 레벨 설정 (설정된 레벨의 로그 출력)
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.SQL: debug
    

# 한글 깨짐으로 인해 추가
server.servlet.encoding.force-response: true